### PR TITLE
refactor: remove leftover pwa code

### PR DESCRIPTION
**Pull request by lmssiehdev**
I'm still not sure why pwa code was removed, there is no alternative yet and I and others still use it with the offline version.

### CODE REVIEW

**Comment by leia-uwu** [comment]
wdym no alternative? the manifest.json works just fine for me

**Comment by lmssiehdev** [comment]
but that doesn't cache assets right? you still have to be connected to the internet to play.

**Comment by leia-uwu** [comment]
yeah it apparently doesn't
maybe we can keep it on offline branch only?

**Comment by lmssiehdev** [comment]
sure, that will do.

**Pull request merged**
